[package]
name = "md5-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # 编译为 Wasm 动态库

[dependencies]
md5 = "0.7.0"        # MD5 算法库
wasm-bindgen = "0.2.92" # 生成 JS 胶水代码
js-sys = "0.3.69"     # JavaScript API 绑定
hex = "0.4.3"         # 二进制转十六进制

